/* server.c generated by valac 0.30.1, the Vala compiler
 * generated from server.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>
#include <json-glib/json-glib.h>


#define TYPE_RESPONSE (response_get_type ())
#define RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_RESPONSE, Response))
#define RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_RESPONSE, ResponseClass))
#define IS_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_RESPONSE))
#define IS_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_RESPONSE))
#define RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_RESPONSE, ResponseClass))

typedef struct _Response Response;
typedef struct _ResponseClass ResponseClass;
typedef struct _ResponsePrivate ResponsePrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_JsonNode_free0(var) ((var == NULL) ? NULL : (var = (_vala_JsonNode_free (var), NULL)))
#define _json_object_unref0(var) ((var == NULL) ? NULL : (var = (json_object_unref (var), NULL)))
#define _vala_assert(expr, msg) if G_LIKELY (expr) ; else g_assertion_message_expr (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);
#define _vala_return_if_fail(expr, msg) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return; }
#define _vala_return_val_if_fail(expr, msg, val) if G_LIKELY (expr) ; else { g_return_if_fail_warning (G_LOG_DOMAIN, G_STRFUNC, msg); return val; }
#define _vala_warn_if_fail(expr, msg) if G_LIKELY (expr) ; else g_warn_message (G_LOG_DOMAIN, __FILE__, __LINE__, G_STRFUNC, msg);

struct _Response {
	GObject parent_instance;
	ResponsePrivate * priv;
	gchar* resp;
	gsize len;
};

struct _ResponseClass {
	GObjectClass parent_class;
};


extern gint headerLen;
gint headerLen = 12;
static gpointer response_parent_class = NULL;

GType response_get_type (void) G_GNUC_CONST;
enum  {
	RESPONSE_DUMMY_PROPERTY
};
Response* response_new (const gchar* resp, gsize len);
Response* response_construct (GType object_type, const gchar* resp, gsize len);
static void response_finalize (GObject* obj);
Response* h264_receive (GSocket* conn, guint8* buffer, int buffer_length1);
gint json_send (const gchar* message, GSocket* conn);
gchar* json_receive (GSocket* conn);
void media_server (GSocketAddress* address);
static JsonNode* _vala_JsonNode_copy (JsonNode* self);
static void _vala_JsonNode_free (JsonNode* self);
void server (GSocketAddress* address);
gint _vala_main (gchar** args, int args_length1);


Response* response_construct (GType object_type, const gchar* resp, gsize len) {
	Response * self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gsize _tmp2_ = 0UL;
	g_return_val_if_fail (resp != NULL, NULL);
	self = (Response*) g_object_new (object_type, NULL);
	_tmp0_ = resp;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->resp);
	self->resp = _tmp1_;
	_tmp2_ = len;
	self->len = _tmp2_;
	return self;
}


Response* response_new (const gchar* resp, gsize len) {
	return response_construct (TYPE_RESPONSE, resp, len);
}


static void response_class_init (ResponseClass * klass) {
	response_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = response_finalize;
}


static void response_instance_init (Response * self) {
}


static void response_finalize (GObject* obj) {
	Response * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_RESPONSE, Response);
	_g_free0 (self->resp);
	G_OBJECT_CLASS (response_parent_class)->finalize (obj);
}


GType response_get_type (void) {
	static volatile gsize response_type_id__volatile = 0;
	if (g_once_init_enter (&response_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (ResponseClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) response_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (Response), 0, (GInstanceInitFunc) response_instance_init, NULL };
		GType response_type_id;
		response_type_id = g_type_register_static (G_TYPE_OBJECT, "Response", &g_define_type_info, 0);
		g_once_init_leave (&response_type_id__volatile, response_type_id);
	}
	return response_type_id__volatile;
}


Response* h264_receive (GSocket* conn, guint8* buffer, int buffer_length1) {
	Response* result = NULL;
	guchar ret[12] = {0};
	gsize len = 0UL;
	GSocket* _tmp0_ = NULL;
	guint8* _tmp1_ = NULL;
	gint _tmp1__length1 = 0;
	gssize _tmp2_ = 0L;
	gchar* _result_ = NULL;
	gchar* _tmp12_ = NULL;
	gboolean _tmp13_ = FALSE;
	guchar _tmp14_ = '\0';
	Response* r = NULL;
	const gchar* _tmp17_ = NULL;
	Response* _tmp18_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (conn != NULL, NULL);
	_tmp0_ = conn;
	_tmp1_ = buffer;
	_tmp1__length1 = buffer_length1;
	_tmp2_ = g_socket_receive (_tmp0_, _tmp1_, (gsize) _tmp1__length1, NULL, &_inner_error_);
	len = (gsize) _tmp2_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	{
		guint j = 0U;
		j = (guint) 0;
		{
			gboolean _tmp3_ = FALSE;
			_tmp3_ = TRUE;
			while (TRUE) {
				guint _tmp5_ = 0U;
				gint _tmp6_ = 0;
				guint _tmp7_ = 0U;
				guint8* _tmp8_ = NULL;
				gint _tmp8__length1 = 0;
				guint _tmp9_ = 0U;
				guint8 _tmp10_ = 0U;
				guchar _tmp11_ = '\0';
				if (!_tmp3_) {
					guint _tmp4_ = 0U;
					_tmp4_ = j;
					j = _tmp4_ + 1;
				}
				_tmp3_ = FALSE;
				_tmp5_ = j;
				_tmp6_ = headerLen;
				if (!(_tmp5_ < ((guint) _tmp6_))) {
					break;
				}
				_tmp7_ = j;
				_tmp8_ = buffer;
				_tmp8__length1 = buffer_length1;
				_tmp9_ = j;
				_tmp10_ = _tmp8_[_tmp9_];
				ret[_tmp7_] = (guchar) _tmp10_;
				_tmp11_ = ret[_tmp7_];
			}
		}
	}
	_tmp12_ = g_strdup ("ok");
	_result_ = _tmp12_;
	_tmp14_ = ret[0];
	if (((gint) _tmp14_) == 0x8) {
		guchar _tmp15_ = '\0';
		_tmp15_ = ret[1];
		_tmp13_ = ((gint) _tmp15_) == 0x2;
	} else {
		_tmp13_ = FALSE;
	}
	if (_tmp13_) {
		gchar* _tmp16_ = NULL;
		_tmp16_ = g_strdup ("header");
		_g_free0 (_result_);
		_result_ = _tmp16_;
	}
	_tmp17_ = _result_;
	_tmp18_ = response_new (_tmp17_, len);
	r = _tmp18_;
	result = r;
	_g_free0 (_result_);
	return result;
}


static guint8* string_get_data (const gchar* self, int* result_length1) {
	guint8* result;
	guint8* res = NULL;
	gint res_length1 = 0;
	gint _res_size_ = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	guint8* _tmp3_ = NULL;
	gint _tmp3__length1 = 0;
	guint8* _tmp4_ = NULL;
	gint _tmp4__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	res = (guint8*) self;
	res_length1 = -1;
	_res_size_ = res_length1;
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	res_length1 = (gint) _tmp1_;
	_tmp2_ = res_length1;
	_tmp3_ = res;
	_tmp3__length1 = res_length1;
	_tmp4_ = _tmp3_;
	_tmp4__length1 = _tmp3__length1;
	if (result_length1) {
		*result_length1 = _tmp4__length1;
	}
	result = _tmp4_;
	return result;
}


gint json_send (const gchar* message, GSocket* conn) {
	gint result = 0;
	guint8 header[12] = {0};
	const gchar* _tmp0_ = NULL;
	gsize _tmp1_ = 0UL;
	guint8 _tmp2_[12] = {0};
	FILE* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	GSocket* _tmp5_ = NULL;
	GSocket* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	guint8* _tmp8_ = NULL;
	gint _tmp8__length1 = 0;
	guint8* _tmp9_ = NULL;
	gint _tmp9__length1 = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (message != NULL, 0);
	g_return_val_if_fail (conn != NULL, 0);
	_tmp0_ = message;
	_tmp1_ = strlen (_tmp0_);
	_tmp2_[0] = (guint8) 0x08;
	_tmp2_[1] = (guint8) 0x00;
	_tmp2_[2] = (guint8) 0x00;
	_tmp2_[3] = (guint8) 0x00;
	_tmp2_[4] = (guint8) 0x00;
	_tmp2_[5] = (guint8) 0x00;
	_tmp2_[6] = (guint8) 0x00;
	_tmp2_[7] = (guint8) _tmp1_;
	_tmp2_[8] = (guint8) 0x52;
	_tmp2_[9] = (guint8) 0x00;
	_tmp2_[10] = (guint8) 0x00;
	_tmp2_[11] = (guint8) 0x00;
	memcpy (header, _tmp2_, 12 * sizeof (guint8));
	_tmp3_ = stdout;
	_tmp4_ = message;
	fprintf (_tmp3_, "\n----\nMessage send: %s\n", _tmp4_);
	_tmp5_ = conn;
	g_socket_send (_tmp5_, header, (gsize) 12, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_tmp6_ = conn;
	_tmp7_ = message;
	_tmp8_ = string_get_data (_tmp7_, &_tmp8__length1);
	_tmp9_ = _tmp8_;
	_tmp9__length1 = _tmp8__length1;
	g_socket_send (_tmp6_, _tmp9_, (gsize) _tmp9__length1, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	result = 0;
	return result;
}


gchar* json_receive (GSocket* conn) {
	gchar* result = NULL;
	guchar ret[12] = {0};
	guint64 payloadLen = 0ULL;
	guint8 buffer[100000] = {0};
	gchar* resp = NULL;
	GSocket* _tmp0_ = NULL;
	FILE* _tmp1_ = NULL;
	guchar _tmp13_ = '\0';
	guchar _tmp14_ = '\0';
	guchar _tmp15_ = '\0';
	guchar _tmp16_ = '\0';
	gint _tmp17_ = 0;
	guint64 _tmp18_ = 0ULL;
	gint _tmp19_ = 0;
	gchar* _tmp20_ = NULL;
	FILE* _tmp21_ = NULL;
	guint64 _tmp22_ = 0ULL;
	gboolean _tmp23_ = FALSE;
	guchar _tmp24_ = '\0';
	gboolean _tmp27_ = FALSE;
	guchar _tmp28_ = '\0';
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (conn != NULL, NULL);
	_tmp0_ = conn;
	g_socket_receive (_tmp0_, buffer, (gsize) 100000, NULL, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_free0 (resp);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
	_tmp1_ = stdout;
	fprintf (_tmp1_, "\nHeader:");
	{
		guint j = 0U;
		j = (guint) 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				guint _tmp4_ = 0U;
				gint _tmp5_ = 0;
				guint _tmp6_ = 0U;
				guint _tmp7_ = 0U;
				guint8 _tmp8_ = 0U;
				guchar _tmp9_ = '\0';
				FILE* _tmp10_ = NULL;
				guint _tmp11_ = 0U;
				guint8 _tmp12_ = 0U;
				if (!_tmp2_) {
					guint _tmp3_ = 0U;
					_tmp3_ = j;
					j = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = j;
				_tmp5_ = headerLen;
				if (!(_tmp4_ < ((guint) _tmp5_))) {
					break;
				}
				_tmp6_ = j;
				_tmp7_ = j;
				_tmp8_ = buffer[_tmp7_];
				ret[_tmp6_] = (guchar) _tmp8_;
				_tmp9_ = ret[_tmp6_];
				_tmp10_ = stdout;
				_tmp11_ = j;
				_tmp12_ = buffer[_tmp11_];
				fprintf (_tmp10_, "%p ", (const gchar*) _tmp12_);
			}
		}
	}
	_tmp13_ = ret[7];
	_tmp14_ = ret[6];
	_tmp15_ = ret[5];
	_tmp16_ = ret[4];
	payloadLen = (guint64) (((_tmp13_ + (_tmp14_ * 0x100)) + (_tmp15_ * 0x10000)) + (_tmp16_ * 0x1000000));
	_tmp17_ = headerLen;
	_tmp18_ = payloadLen;
	_tmp19_ = headerLen;
	_tmp20_ = g_strdup ((const gchar*) (buffer + _tmp17_));
	_g_free0 (resp);
	resp = _tmp20_;
	_tmp21_ = stdout;
	_tmp22_ = payloadLen;
	fprintf (_tmp21_, "PayloadLen: %" G_GUINT64_FORMAT "\n", _tmp22_);
	_tmp24_ = ret[0];
	if (((gint) _tmp24_) == 0x8) {
		guchar _tmp25_ = '\0';
		_tmp25_ = ret[1];
		_tmp23_ = ((gint) _tmp25_) == 0x2;
	} else {
		_tmp23_ = FALSE;
	}
	if (_tmp23_) {
		gchar* _tmp26_ = NULL;
		_tmp26_ = g_strdup ("h264");
		result = _tmp26_;
		_g_free0 (resp);
		return result;
	}
	_tmp28_ = ret[1];
	if (((gint) _tmp28_) == 0x16) {
		_tmp27_ = TRUE;
	} else {
		guchar _tmp29_ = '\0';
		_tmp29_ = ret[0];
		_tmp27_ = ((gint) _tmp29_) != 0x8;
	}
	if (_tmp27_) {
		gchar* _tmp30_ = NULL;
		_tmp30_ = g_strdup ("error");
		result = _tmp30_;
		_g_free0 (resp);
		return result;
	}
	result = resp;
	return result;
}


static JsonNode* _vala_JsonNode_copy (JsonNode* self) {
	return g_boxed_copy (json_node_get_type (), self);
}


static gpointer __vala_JsonNode_copy0 (gpointer self) {
	return self ? _vala_JsonNode_copy (self) : NULL;
}


static const gchar* string_to_string (const gchar* self) {
	const gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	result = self;
	return result;
}


static void _vala_JsonNode_free (JsonNode* self) {
	g_boxed_free (json_node_get_type (), self);
}


void media_server (GSocketAddress* address) {
	FILE* _tmp0_ = NULL;
	GSocket* socket = NULL;
	GSocket* _tmp1_ = NULL;
	GSocket* _tmp2_ = NULL;
	GSocket* _tmp3_ = NULL;
	GSocketAddress* _tmp4_ = NULL;
	GSocket* _tmp5_ = NULL;
	GSocket* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (address != NULL);
	_tmp0_ = stdout;
	fputs ("----------media_server--------------\n", _tmp0_);
	_tmp1_ = g_socket_new (G_SOCKET_FAMILY_IPV4, G_SOCKET_TYPE_STREAM, G_SOCKET_PROTOCOL_TCP, &_inner_error_);
	socket = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = socket;
	_vala_assert (_tmp2_ != NULL, "socket != null");
	_tmp3_ = socket;
	_tmp4_ = address;
	g_socket_bind (_tmp3_, _tmp4_, TRUE, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (socket);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = socket;
	g_socket_set_listen_backlog (_tmp5_, 10);
	_tmp6_ = socket;
	g_socket_listen (_tmp6_, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (socket);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp7_ = FALSE;
			_tmp7_ = TRUE;
			while (TRUE) {
				gchar* response = NULL;
				GSocket* connection = NULL;
				GSocket* _tmp9_ = NULL;
				GSocket* _tmp10_ = NULL;
				gchar* ses = NULL;
				guint8 buffer[2000000] = {0};
				GFile* file = NULL;
				GFile* _tmp11_ = NULL;
				GFile* _tmp12_ = NULL;
				gboolean _tmp13_ = FALSE;
				GFileOutputStream* _tmp15_ = NULL;
				GFile* _tmp16_ = NULL;
				GFileOutputStream* _tmp17_ = NULL;
				GDataOutputStream* dos = NULL;
				GDataOutputStream* _tmp18_ = NULL;
				glong written = 0L;
				Response* r = NULL;
				FILE* _tmp19_ = NULL;
				gint _tmp20_ = 0;
				GSocket* _tmp21_ = NULL;
				gchar* _tmp22_ = NULL;
				FILE* _tmp23_ = NULL;
				const gchar* _tmp24_ = NULL;
				JsonParser* parser = NULL;
				JsonParser* _tmp25_ = NULL;
				JsonParser* _tmp26_ = NULL;
				const gchar* _tmp27_ = NULL;
				const gchar* _tmp28_ = NULL;
				gint _tmp29_ = 0;
				gint _tmp30_ = 0;
				JsonNode* node = NULL;
				JsonParser* _tmp31_ = NULL;
				JsonNode* _tmp32_ = NULL;
				JsonNode* _tmp33_ = NULL;
				JsonNode* _tmp34_ = NULL;
				JsonObject* _tmp35_ = NULL;
				const gchar* _tmp36_ = NULL;
				gchar* _tmp37_ = NULL;
				gchar* create = NULL;
				const gchar* _tmp38_ = NULL;
				const gchar* _tmp39_ = NULL;
				gchar* _tmp40_ = NULL;
				gchar* controlstream = NULL;
				const gchar* _tmp41_ = NULL;
				const gchar* _tmp42_ = NULL;
				gchar* _tmp43_ = NULL;
				const gchar* _tmp44_ = NULL;
				GSocket* _tmp45_ = NULL;
				GSocket* _tmp46_ = NULL;
				gchar* _tmp47_ = NULL;
				const gchar* _tmp48_ = NULL;
				GSocket* _tmp76_ = NULL;
				GDataOutputStream* _tmp77_ = NULL;
				if (!_tmp7_) {
					gint _tmp8_ = 0;
					_tmp8_ = i;
					i = (_tmp8_ + 1) % 10;
				}
				_tmp7_ = FALSE;
				_tmp9_ = socket;
				_tmp10_ = g_socket_accept (_tmp9_, NULL, &_inner_error_);
				connection = _tmp10_;
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_free0 (response);
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_tmp11_ = g_file_new_for_path ("out2.h264");
				file = _tmp11_;
				_tmp12_ = file;
				_tmp13_ = g_file_query_exists (_tmp12_, NULL);
				if (_tmp13_) {
					GFile* _tmp14_ = NULL;
					_tmp14_ = file;
					g_file_delete (_tmp14_, NULL, &_inner_error_);
					if (G_UNLIKELY (_inner_error_ != NULL)) {
						_g_object_unref0 (file);
						_g_free0 (ses);
						_g_object_unref0 (connection);
						_g_free0 (response);
						_g_object_unref0 (socket);
						g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
						g_clear_error (&_inner_error_);
						return;
					}
				}
				_tmp16_ = file;
				_tmp17_ = g_file_create (_tmp16_, G_FILE_CREATE_REPLACE_DESTINATION, NULL, &_inner_error_);
				_tmp15_ = _tmp17_;
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_object_unref0 (file);
					_g_free0 (ses);
					_g_object_unref0 (connection);
					_g_free0 (response);
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_tmp18_ = g_data_output_stream_new ((GOutputStream*) _tmp15_);
				dos = _tmp18_;
				written = (glong) 0;
				_tmp19_ = stdout;
				_tmp20_ = i;
				fprintf (_tmp19_, "accepted (%d)\n", _tmp20_);
				_tmp21_ = connection;
				_tmp22_ = json_receive (_tmp21_);
				_g_free0 (response);
				response = _tmp22_;
				_tmp23_ = stdout;
				_tmp24_ = response;
				fprintf (_tmp23_, "Response:%s\n", _tmp24_);
				_tmp25_ = json_parser_new ();
				parser = _tmp25_;
				_tmp26_ = parser;
				_tmp27_ = response;
				_tmp28_ = response;
				_tmp29_ = strlen (_tmp28_);
				_tmp30_ = _tmp29_;
				json_parser_load_from_data (_tmp26_, _tmp27_, (gssize) _tmp30_, &_inner_error_);
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_object_unref0 (parser);
					_g_object_unref0 (r);
					_g_object_unref0 (dos);
					_g_object_unref0 (_tmp15_);
					_g_object_unref0 (file);
					_g_free0 (ses);
					_g_object_unref0 (connection);
					_g_free0 (response);
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_tmp31_ = parser;
				_tmp32_ = json_parser_get_root (_tmp31_);
				_tmp33_ = __vala_JsonNode_copy0 (_tmp32_);
				node = _tmp33_;
				_tmp34_ = node;
				_tmp35_ = json_node_get_object (_tmp34_);
				_tmp36_ = json_object_get_string_member (_tmp35_, "SESSION");
				_tmp37_ = g_strdup (_tmp36_);
				_g_free0 (ses);
				ses = _tmp37_;
				_tmp38_ = ses;
				_tmp39_ = string_to_string (_tmp38_);
				_tmp40_ = g_strconcat ("{\"MODULE\":\"CERTIFICATE\",\"OPERATION\":\"CREATESTREAM\",\"PARAMETER" \
"\":{\"ERRORCODE\":0,\"ERRORCAUSE\":\"1\"},\"SESSION\":\"", _tmp39_, "\"}\r\n", NULL);
				create = _tmp40_;
				_tmp41_ = ses;
				_tmp42_ = string_to_string (_tmp41_);
				_tmp43_ = g_strconcat ("{\"PARAMETER\":{\"SSRC\":0,\"STREAMTYPE\":0,\"PT\":2,\"STREAMNAME\":\"" \
"STREAM-9\",\"AUDIOVALID\":1,\"CMD\":\"0\"},\"OPERATION\":\"CONTROLSTRE" \
"AM\",\"SESSION\":\"", _tmp42_, "\",\"MODULE\":\"MEDIASTREAMMODEL\"}\r\n", NULL);
				controlstream = _tmp43_;
				_tmp44_ = create;
				_tmp45_ = connection;
				json_send (_tmp44_, _tmp45_);
				_tmp46_ = connection;
				_tmp47_ = json_receive (_tmp46_);
				_g_free0 (response);
				response = _tmp47_;
				_tmp48_ = response;
				if (g_strcmp0 (_tmp48_, "h264") == 0) {
					while (TRUE) {
						GSocket* _tmp49_ = NULL;
						Response* _tmp50_ = NULL;
						FILE* _tmp54_ = NULL;
						FILE* _tmp55_ = NULL;
						Response* _tmp56_ = NULL;
						gsize _tmp57_ = 0UL;
						FILE* _tmp68_ = NULL;
						_tmp49_ = connection;
						_tmp50_ = h264_receive (_tmp49_, buffer, 2000000);
						_g_object_unref0 (r);
						r = _tmp50_;
						while (TRUE) {
							const gchar* _tmp51_ = NULL;
							GSocket* _tmp52_ = NULL;
							Response* _tmp53_ = NULL;
							_tmp51_ = response;
							if (!(g_strcmp0 (_tmp51_, "header") == 0)) {
								break;
							}
							_tmp52_ = connection;
							_tmp53_ = h264_receive (_tmp52_, buffer, 2000000);
							_g_object_unref0 (r);
							r = _tmp53_;
						}
						_tmp54_ = stdout;
						fprintf (_tmp54_, "DATA:%s\n", (const gchar*) buffer);
						_tmp55_ = stdout;
						_tmp56_ = r;
						_tmp57_ = _tmp56_->len;
						fprintf (_tmp55_, "Buffer len: %" G_GSIZE_FORMAT "\n", _tmp57_);
						while (TRUE) {
							glong _tmp58_ = 0L;
							Response* _tmp59_ = NULL;
							gsize _tmp60_ = 0UL;
							gssize _tmp61_ = 0L;
							GDataOutputStream* _tmp62_ = NULL;
							glong _tmp63_ = 0L;
							Response* _tmp64_ = NULL;
							gsize _tmp65_ = 0UL;
							gssize _tmp66_ = 0L;
							glong _tmp67_ = 0L;
							_tmp58_ = written;
							_tmp59_ = r;
							_tmp60_ = _tmp59_->len;
							if (!(((gsize) _tmp58_) < _tmp60_)) {
								break;
							}
							_tmp62_ = dos;
							_tmp63_ = written;
							_tmp64_ = r;
							_tmp65_ = _tmp64_->len;
							_tmp66_ = g_output_stream_write ((GOutputStream*) _tmp62_, buffer + ((gint) _tmp63_), (gsize) (((gint) _tmp65_) - ((gint) _tmp63_)), NULL, &_inner_error_);
							_tmp61_ = _tmp66_;
							if (G_UNLIKELY (_inner_error_ != NULL)) {
								_g_free0 (controlstream);
								_g_free0 (create);
								__vala_JsonNode_free0 (node);
								_g_object_unref0 (parser);
								_g_object_unref0 (r);
								_g_object_unref0 (dos);
								_g_object_unref0 (_tmp15_);
								_g_object_unref0 (file);
								_g_free0 (ses);
								_g_object_unref0 (connection);
								_g_free0 (response);
								_g_object_unref0 (socket);
								g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
								g_clear_error (&_inner_error_);
								return;
							}
							_tmp67_ = written;
							written = _tmp67_ + _tmp61_;
						}
						written = (glong) 0;
						_tmp68_ = stdout;
						fputs ("Receive h.264 data\n", _tmp68_);
					}
				}
				{
					gint j = 0;
					j = 0;
					{
						gboolean _tmp69_ = FALSE;
						_tmp69_ = TRUE;
						while (TRUE) {
							gint _tmp71_ = 0;
							GSocket* _tmp72_ = NULL;
							gchar* _tmp73_ = NULL;
							FILE* _tmp74_ = NULL;
							const gchar* _tmp75_ = NULL;
							if (!_tmp69_) {
								gint _tmp70_ = 0;
								_tmp70_ = j;
								j = _tmp70_ + 1;
							}
							_tmp69_ = FALSE;
							_tmp71_ = j;
							if (!(_tmp71_ < 5)) {
								break;
							}
							_tmp72_ = connection;
							_tmp73_ = json_receive (_tmp72_);
							_g_free0 (response);
							response = _tmp73_;
							_tmp74_ = stdout;
							_tmp75_ = response;
							fprintf (_tmp74_, "Response 2:%s\n", _tmp75_);
						}
					}
				}
				_tmp76_ = connection;
				g_socket_close (_tmp76_, &_inner_error_);
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_free0 (controlstream);
					_g_free0 (create);
					__vala_JsonNode_free0 (node);
					_g_object_unref0 (parser);
					_g_object_unref0 (r);
					_g_object_unref0 (dos);
					_g_object_unref0 (_tmp15_);
					_g_object_unref0 (file);
					_g_free0 (ses);
					_g_object_unref0 (connection);
					_g_free0 (response);
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_tmp77_ = dos;
				g_output_stream_close ((GOutputStream*) _tmp77_, NULL, &_inner_error_);
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_free0 (controlstream);
					_g_free0 (create);
					__vala_JsonNode_free0 (node);
					_g_object_unref0 (parser);
					_g_object_unref0 (r);
					_g_object_unref0 (dos);
					_g_object_unref0 (_tmp15_);
					_g_object_unref0 (file);
					_g_free0 (ses);
					_g_object_unref0 (connection);
					_g_free0 (response);
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_g_free0 (controlstream);
				_g_free0 (create);
				__vala_JsonNode_free0 (node);
				_g_object_unref0 (parser);
				_g_object_unref0 (r);
				_g_object_unref0 (dos);
				_g_object_unref0 (_tmp15_);
				_g_object_unref0 (file);
				_g_free0 (ses);
				_g_object_unref0 (connection);
				_g_free0 (response);
				_g_object_unref0 (socket);
				return;
			}
		}
	}
	_g_object_unref0 (socket);
}


static gpointer _json_object_ref0 (gpointer self) {
	return self ? json_object_ref (self) : NULL;
}


void server (GSocketAddress* address) {
	FILE* _tmp0_ = NULL;
	GSocket* socket = NULL;
	GSocket* _tmp1_ = NULL;
	GSocket* _tmp2_ = NULL;
	GSocket* _tmp3_ = NULL;
	GSocketAddress* _tmp4_ = NULL;
	GSocket* _tmp5_ = NULL;
	GSocket* _tmp6_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (address != NULL);
	_tmp0_ = stdout;
	fputs ("----------server--------------\n", _tmp0_);
	_tmp1_ = g_socket_new (G_SOCKET_FAMILY_IPV4, G_SOCKET_TYPE_STREAM, G_SOCKET_PROTOCOL_TCP, &_inner_error_);
	socket = _tmp1_;
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp2_ = socket;
	_vala_assert (_tmp2_ != NULL, "socket != null");
	_tmp3_ = socket;
	_tmp4_ = address;
	g_socket_bind (_tmp3_, _tmp4_, TRUE, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (socket);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp5_ = socket;
	g_socket_set_listen_backlog (_tmp5_, 10);
	_tmp6_ = socket;
	g_socket_listen (_tmp6_, &_inner_error_);
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		_g_object_unref0 (socket);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp7_ = FALSE;
			_tmp7_ = TRUE;
			while (TRUE) {
				GSocket* connection = NULL;
				GSocket* _tmp9_ = NULL;
				GSocket* _tmp10_ = NULL;
				FILE* _tmp11_ = NULL;
				gint _tmp12_ = 0;
				gchar* response = NULL;
				gchar* ses = NULL;
				gchar* dsno = NULL;
				gchar* pro = NULL;
				gchar* operation = NULL;
				gchar* _tmp13_ = NULL;
				gchar* s0 = NULL;
				GSocket* _tmp14_ = NULL;
				gchar* _tmp15_ = NULL;
				FILE* _tmp16_ = NULL;
				const gchar* _tmp17_ = NULL;
				JsonParser* parser = NULL;
				JsonParser* _tmp18_ = NULL;
				JsonParser* _tmp19_ = NULL;
				const gchar* _tmp20_ = NULL;
				const gchar* _tmp21_ = NULL;
				gint _tmp22_ = 0;
				gint _tmp23_ = 0;
				JsonNode* node = NULL;
				JsonParser* _tmp24_ = NULL;
				JsonNode* _tmp25_ = NULL;
				JsonNode* _tmp26_ = NULL;
				JsonNode* _tmp27_ = NULL;
				JsonObject* _tmp28_ = NULL;
				const gchar* _tmp29_ = NULL;
				gchar* _tmp30_ = NULL;
				JsonObject* parameter = NULL;
				JsonNode* _tmp31_ = NULL;
				JsonObject* _tmp32_ = NULL;
				JsonObject* _tmp33_ = NULL;
				JsonObject* _tmp34_ = NULL;
				JsonObject* _tmp35_ = NULL;
				const gchar* _tmp36_ = NULL;
				gchar* _tmp37_ = NULL;
				JsonObject* _tmp38_ = NULL;
				const gchar* _tmp39_ = NULL;
				gchar* _tmp40_ = NULL;
				FILE* _tmp41_ = NULL;
				const gchar* _tmp42_ = NULL;
				FILE* _tmp43_ = NULL;
				const gchar* _tmp44_ = NULL;
				FILE* _tmp45_ = NULL;
				const gchar* _tmp46_ = NULL;
				gchar* reboot = NULL;
				const gchar* _tmp47_ = NULL;
				const gchar* _tmp48_ = NULL;
				gchar* _tmp49_ = NULL;
				gchar* keepalive = NULL;
				const gchar* _tmp50_ = NULL;
				const gchar* _tmp51_ = NULL;
				gchar* _tmp52_ = NULL;
				gchar* connect = NULL;
				const gchar* _tmp53_ = NULL;
				const gchar* _tmp54_ = NULL;
				gchar* _tmp55_ = NULL;
				gchar* requestalivevideo = NULL;
				const gchar* _tmp56_ = NULL;
				const gchar* _tmp57_ = NULL;
				gchar* _tmp58_ = NULL;
				gchar* controlstream = NULL;
				const gchar* _tmp59_ = NULL;
				const gchar* _tmp60_ = NULL;
				gchar* _tmp61_ = NULL;
				gchar* getcalendar = NULL;
				const gchar* _tmp62_ = NULL;
				const gchar* _tmp63_ = NULL;
				gchar* _tmp64_ = NULL;
				const gchar* _tmp65_ = NULL;
				GSocket* _tmp66_ = NULL;
				GSocket* _tmp67_ = NULL;
				gchar* _tmp68_ = NULL;
				gchar* _tmp69_ = NULL;
				const gchar* _tmp70_ = NULL;
				GSocket* _tmp71_ = NULL;
				GInetAddress* media_server_address = NULL;
				GInetAddress* _tmp78_ = NULL;
				GInetSocketAddress* media_address = NULL;
				GInetAddress* _tmp79_ = NULL;
				GInetSocketAddress* _tmp80_ = NULL;
				GInetSocketAddress* _tmp81_ = NULL;
				GSocket* _tmp89_ = NULL;
				FILE* _tmp90_ = NULL;
				if (!_tmp7_) {
					gint _tmp8_ = 0;
					_tmp8_ = i;
					i = (_tmp8_ + 1) % 10;
				}
				_tmp7_ = FALSE;
				_tmp9_ = socket;
				_tmp10_ = g_socket_accept (_tmp9_, NULL, &_inner_error_);
				connection = _tmp10_;
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_tmp11_ = stdout;
				_tmp12_ = i;
				fprintf (_tmp11_, "accepted (%d)\n", _tmp12_);
				_tmp13_ = g_strdup ("");
				operation = _tmp13_;
				_tmp14_ = connection;
				_tmp15_ = json_receive (_tmp14_);
				_g_free0 (response);
				response = _tmp15_;
				_tmp16_ = stdout;
				_tmp17_ = response;
				fprintf (_tmp16_, "Response:%s\n", _tmp17_);
				_tmp18_ = json_parser_new ();
				parser = _tmp18_;
				_tmp19_ = parser;
				_tmp20_ = response;
				_tmp21_ = response;
				_tmp22_ = strlen (_tmp21_);
				_tmp23_ = _tmp22_;
				json_parser_load_from_data (_tmp19_, _tmp20_, (gssize) _tmp23_, &_inner_error_);
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_object_unref0 (parser);
					_g_free0 (s0);
					_g_free0 (operation);
					_g_free0 (pro);
					_g_free0 (dsno);
					_g_free0 (ses);
					_g_free0 (response);
					_g_object_unref0 (connection);
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_tmp24_ = parser;
				_tmp25_ = json_parser_get_root (_tmp24_);
				_tmp26_ = __vala_JsonNode_copy0 (_tmp25_);
				node = _tmp26_;
				_tmp27_ = node;
				_tmp28_ = json_node_get_object (_tmp27_);
				_tmp29_ = json_object_get_string_member (_tmp28_, "SESSION");
				_tmp30_ = g_strdup (_tmp29_);
				_g_free0 (ses);
				ses = _tmp30_;
				_tmp31_ = node;
				_tmp32_ = json_node_get_object (_tmp31_);
				_tmp33_ = json_object_get_object_member (_tmp32_, "PARAMETER");
				_tmp34_ = _json_object_ref0 (_tmp33_);
				parameter = _tmp34_;
				_tmp35_ = parameter;
				_tmp36_ = json_object_get_string_member (_tmp35_, "DSNO");
				_tmp37_ = g_strdup (_tmp36_);
				_g_free0 (dsno);
				dsno = _tmp37_;
				_tmp38_ = parameter;
				_tmp39_ = json_object_get_string_member (_tmp38_, "PRO");
				_tmp40_ = g_strdup (_tmp39_);
				_g_free0 (pro);
				pro = _tmp40_;
				_tmp41_ = stdout;
				_tmp42_ = ses;
				fprintf (_tmp41_, "Session:%s\n", _tmp42_);
				_tmp43_ = stdout;
				_tmp44_ = dsno;
				fprintf (_tmp43_, "DSNO:%s\n", _tmp44_);
				_tmp45_ = stdout;
				_tmp46_ = pro;
				fprintf (_tmp45_, "PRO:%s\n", _tmp46_);
				_tmp47_ = ses;
				_tmp48_ = string_to_string (_tmp47_);
				_tmp49_ = g_strconcat ("{\"MODULE\":\"DISCOVERY\",\"OPERATION\":\"REBOOT\",\"SESSION\":\"", _tmp48_, "\"}\r\n", NULL);
				reboot = _tmp49_;
				_tmp50_ = ses;
				_tmp51_ = string_to_string (_tmp50_);
				_tmp52_ = g_strconcat ("{\"MODULE\":\"CERTIFICATE\",\"OPERATION\":\"KEEPALIVE\",\"SESSION\":\"", _tmp51_, "\"}\r\n", NULL);
				keepalive = _tmp52_;
				_tmp53_ = ses;
				_tmp54_ = string_to_string (_tmp53_);
				_tmp55_ = g_strconcat ("{\"MODULE\":\"CERTIFICATE\",\"OPERATION\":\"CONNECT\",\"RESPONSE\":{\"" \
"SO\":\"1234\"\"ERRORCODE\":0,\"ERRORCAUSE\":\"1\"},\"SESSION\":\"", _tmp54_, "\"}\r\n", NULL);
				connect = _tmp55_;
				_tmp56_ = ses;
				_tmp57_ = string_to_string (_tmp56_);
				_tmp58_ = g_strconcat ("{\"PARAMETER\":{\"CHANNEL\":2,\"SERIAL\":0,\"STREAMTYPE\":0,\"IPANDPOR" \
"T\":\"10.0.0.3:5557\",\"STREAMNAME\":\"STREAM-9\",\"AUDIOVALID\":1},\"" \
"OPERATION\":\"REQUESTALIVEVIDEO\",\"SESSION\":\"", _tmp57_, "\",\"MODULE\":\"MEDIASTREAMMODEL\"}\r\n", NULL);
				requestalivevideo = _tmp58_;
				_tmp59_ = ses;
				_tmp60_ = string_to_string (_tmp59_);
				_tmp61_ = g_strconcat ("{\"PARAMETER\":{\"SSRC\":0,\"STREAMTYPE\":0,\"PT\":2,\"STREAMNAME\":\"" \
"STREAM-9\",\"AUDIOVALID\":1,\"CMD\":\"0\"},\"OPERATION\":\"CONTROLSTRE" \
"AM\",\"SESSION\":\"", _tmp60_, "\",\"MODULE\":\"MEDIASTREAMMODEL\"}\r\n", NULL);
				controlstream = _tmp61_;
				_tmp62_ = ses;
				_tmp63_ = string_to_string (_tmp62_);
				_tmp64_ = g_strconcat ("{\"PARAMETER\":{\"FILETYPE\":65535,\"CHANNEL\":4294967295,\"CALENDARTY" \
"PE\":2,\"SERIAL\":0,\"STREAMTYPE\":1},\"OPERATION\":\"GETCALENDAR\",\"" \
"SESSION\":\"", _tmp63_, "\",\"MODULE\":\"STORM\"}\r\n", NULL);
				getcalendar = _tmp64_;
				_tmp65_ = connect;
				_tmp66_ = connection;
				json_send (_tmp65_, _tmp66_);
				_tmp67_ = connection;
				_tmp68_ = json_receive (_tmp67_);
				_tmp69_ = _tmp68_;
				_g_free0 (_tmp69_);
				_tmp70_ = requestalivevideo;
				_tmp71_ = connection;
				json_send (_tmp70_, _tmp71_);
				{
					gboolean _tmp72_ = FALSE;
					_tmp72_ = TRUE;
					while (TRUE) {
						GSocket* _tmp74_ = NULL;
						gchar* _tmp75_ = NULL;
						FILE* _tmp76_ = NULL;
						const gchar* _tmp77_ = NULL;
						if (!_tmp72_) {
							const gchar* _tmp73_ = NULL;
							_tmp73_ = response;
							if (!(g_strcmp0 (_tmp73_, "error") == 0)) {
								break;
							}
						}
						_tmp72_ = FALSE;
						_tmp74_ = connection;
						_tmp75_ = json_receive (_tmp74_);
						_g_free0 (response);
						response = _tmp75_;
						_tmp76_ = stdout;
						_tmp77_ = response;
						fprintf (_tmp76_, "3 Response:%s\n", _tmp77_);
					}
				}
				_tmp78_ = g_inet_address_new_from_string ("10.0.0.3");
				media_server_address = _tmp78_;
				_tmp79_ = media_server_address;
				_tmp80_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp79_, (guint16) 5557);
				media_address = _tmp80_;
				_tmp81_ = media_address;
				media_server ((GSocketAddress*) _tmp81_);
				{
					gint j = 0;
					j = 0;
					{
						gboolean _tmp82_ = FALSE;
						_tmp82_ = TRUE;
						while (TRUE) {
							gint _tmp84_ = 0;
							GSocket* _tmp85_ = NULL;
							gchar* _tmp86_ = NULL;
							FILE* _tmp87_ = NULL;
							const gchar* _tmp88_ = NULL;
							if (!_tmp82_) {
								gint _tmp83_ = 0;
								_tmp83_ = j;
								j = _tmp83_ + 1;
							}
							_tmp82_ = FALSE;
							_tmp84_ = j;
							if (!(_tmp84_ < 5)) {
								break;
							}
							_tmp85_ = connection;
							_tmp86_ = json_receive (_tmp85_);
							_g_free0 (response);
							response = _tmp86_;
							_tmp87_ = stdout;
							_tmp88_ = response;
							fprintf (_tmp87_, "5 Response:%s\n", _tmp88_);
						}
					}
				}
				_tmp89_ = connection;
				g_socket_close (_tmp89_, &_inner_error_);
				if (G_UNLIKELY (_inner_error_ != NULL)) {
					_g_object_unref0 (media_address);
					_g_object_unref0 (media_server_address);
					_g_free0 (getcalendar);
					_g_free0 (controlstream);
					_g_free0 (requestalivevideo);
					_g_free0 (connect);
					_g_free0 (keepalive);
					_g_free0 (reboot);
					_json_object_unref0 (parameter);
					__vala_JsonNode_free0 (node);
					_g_object_unref0 (parser);
					_g_free0 (s0);
					_g_free0 (operation);
					_g_free0 (pro);
					_g_free0 (dsno);
					_g_free0 (ses);
					_g_free0 (response);
					_g_object_unref0 (connection);
					_g_object_unref0 (socket);
					g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
					g_clear_error (&_inner_error_);
					return;
				}
				_tmp90_ = stdout;
				fputs ("\n" \
"----------------------------------------------------------------------" \
"-----------------------------------------\n", _tmp90_);
				_g_object_unref0 (media_address);
				_g_object_unref0 (media_server_address);
				_g_free0 (getcalendar);
				_g_free0 (controlstream);
				_g_free0 (requestalivevideo);
				_g_free0 (connect);
				_g_free0 (keepalive);
				_g_free0 (reboot);
				_json_object_unref0 (parameter);
				__vala_JsonNode_free0 (node);
				_g_object_unref0 (parser);
				_g_free0 (s0);
				_g_free0 (operation);
				_g_free0 (pro);
				_g_free0 (dsno);
				_g_free0 (ses);
				_g_free0 (response);
				_g_object_unref0 (connection);
			}
		}
	}
	_g_object_unref0 (socket);
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	GInetAddress* server_address = NULL;
	GInetAddress* _tmp2_ = NULL;
	GInetSocketAddress* address = NULL;
	GInetAddress* _tmp3_ = NULL;
	GInetSocketAddress* _tmp4_ = NULL;
	GInetSocketAddress* _tmp5_ = NULL;
	_tmp0_ = g_thread_supported ();
	if (!_tmp0_) {
		FILE* _tmp1_ = NULL;
		_tmp1_ = stderr;
		fprintf (_tmp1_, "Cannot run without threads.\n");
		result = 1;
		return result;
	}
	_tmp2_ = g_inet_address_new_from_string ("10.0.0.3");
	server_address = _tmp2_;
	_tmp3_ = server_address;
	_tmp4_ = (GInetSocketAddress*) g_inet_socket_address_new (_tmp3_, (guint16) 5556);
	address = _tmp4_;
	_tmp5_ = address;
	server ((GSocketAddress*) _tmp5_);
	result = 0;
	_g_object_unref0 (address);
	_g_object_unref0 (server_address);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



